services:
  clients_api:
    build: ./clientsApi
    #command: 'tail -f /dev/null'
    command: 'bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"'
    volumes:
      - ./clientsApi:/app
      - bundle_data:/usr/local/bundle
    ports:
      - "3001:3000"
    depends_on:
      - clients_db
    
    environment:
      RAILS_ENV: development
      DB_HOST: clients_db
      DB_NAME: clients_db
      DB_USER: user
      DB_PASSWORD: password

  clients_db:
    image: postgres:16

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: clients_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - clients_data:/var/lib/postgresql/data

  products_api:
    build: ./productsApi
    #command: 'tail -f /dev/null'
    command: 'bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"'
    volumes:
      - ./productsApi:/app
    ports:
      - "3002:3000"
    depends_on:
      - products_db
    environment:
      RAILS_ENV: development
      DB_HOST: products_db
      DB_NAME: products_db
      DB_USER: user
      DB_PASSWORD: password

  products_db:
    image: postgres:16

    ports:
      - "5433:5432"

    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - products_data:/var/lib/postgresql/data

  sales_api:
    build: ./salesApi
    command: 'tail -f /dev/null'
    volumes:
      - ./salesApi:/app
    ports:
      - "3003:3000"
    depends_on:
      - sales_db
    environment:
      DB_HOST: sales_db
      DB_NAME: sales_db
      DB_USER: user
      DB_PASSWORD: password
      DATABASE_URL: postgres://user:password@sales_db:5432/sales_db
  sales_db:
    image: postgres:16

    ports:
      - "5434:5432"

    environment:
      POSTGRES_DB: sales_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - sales_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    command: 'tail -f /dev/null'
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

volumes:
  clients_data:
  products_data:
  sales_data:
  bundle_data:
